#version: "3"
#services:
pihole:
  image: diginc/pi-hole:arm
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "80:80/tcp"
  environment:
    # enter your docker host IP here
    ServerIP: 10.1.1.171
    # IPv6 Address if your network supports it
    #ServerIPv6: 192.168.1.55
    # jwilder/proxy envs, see readme for more info
    PROXY_LOCATION: pihole
    VIRTUAL_HOST: pihole.pouliot.net
    VIRTUAL_PORT: 80
  # Add your own custom hostnames you need for your domain
  extra_hosts:
    #   Point any of the jwilder virtual_host addresses
    # to your docker host ip address
    - 'bp2.pouliot.net:10.1.1.171'
  volumes:
    - '/etc/pihole/:/etc/pihole/'
    # WARNING: if this log don't exist as a file on the host already
    # docker will try to create a directory in it's place making for lots of errors
    - '/var/log/pihole.log:/var/log/pihole.log'
  restart: always
